#!/usr/bin/env zsh

# Zsh configuration

# With help from these sources:
# https://github.com/slashbeast/things/blob/master/configs/DOTzshrc
# https://github.com/spicycode/ze-best-zsh-config
# http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/

autoload -U compinit promptinit colors vcs_info
colors
compinit
promptinit

test -r $HOME/.aliases && source $HOME/.aliases
test -r $HOME/.exports_local.zsh && source $HOME/.exports_local.zsh
test -r $HOME/dotfiles/zsh/rsf.zsh && source $HOME/dotfiles/zsh/rsf.zsh

for i in $HOME/.zsh.d/*; do;
    test -r "$i" && source "$i"
done

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

#switch on transparent xterm
[ -n "$XTERM_VERSION" ] && transset-df 0.92 --id "$WINDOWID" >/dev/null
